sudo: false
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install tox-travis coveralls
script: tox
after-success: coveralls
branches:
  only:
    - develop
    - master
